name: DevSecOps CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Quality Gate (Check HTML)
        run: |
          if [ -f "index.html" ]; then
            echo "SUCCESS: index.html exists."
          else
            echo "ERROR: index.html missing!"
            exit 1
          fi

      # DevSecOps Step: Scan repository for vulnerabilities
      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Build & Package
        run: echo "Build passed all quality & security checks!"
