name: DevSecOps CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Quality Gate (Check HTML)
        run: |
          if [ -f "index.html" ]; then
            echo "SUCCESS: index.html exists."
          else
            echo "ERROR: index.html missing!"
            exit 1
          fi

      - name: Security Scan Code (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Docker Step: Build the container image
      - name: Build Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .
          echo "Docker image built successfully!"
